name: Draft prerelease # Stole this from ArmCord
on:
  workflow_dispatch

env:
  FORCE_COLOR: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2 # Install pnpm using packageManager key in package.json

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install Node dependencies
        run: pnpm i
        
      - name: Install asar
        run: pnpm i @electron/asar -g

      - name: Build
        run: pnpm build
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app.asar
          path: dist/app.asar

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: app.asar
          path: release

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      #- uses: dev-drprasad/delete-tag-and-release@v0.2.1
      #  with:
      #    delete_release: true
      #    tag_name: ${{ steps.package-version.outputs.current-version}}
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Never again ;-;

      - name: Create the release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package-version.outputs.current-version}}-prerelease
          name: [Prerelease] Oculus Dummy - ${{ steps.package-version.outputs.current-version}}
          draft: true
          prerelease: true
          body_path: .github/prerelease.md
          files: |
            release/app.asar
