name: Draft release # Stole this from ArmCord
on:
  workflow_dispatch

env:
  FORCE_COLOR: true

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2 # Install pnpm using packageManager key in package.json

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install Node dependencies
        run: pnpm i
        
      - name: Install asar
        run: pnpm i @electron/asar -g

      - name: Build
        run: pnpm build
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app.asar
          path: dist/app.asar

  release:
    runs-on: ubuntu-latest
    needs: [build-windows]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: app.asar
          path: windows

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Get some values needed for the release
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: ${{ steps.package-version.outputs.current-version}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create the release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package-version.outputs.current-version}}
          name: Test Build ${{ steps.vars.outputs.sha_short }}
          draft: true
          prerelease: false
          body_path: .github/release.md
          files: |
            windows/app.asar
